package com.github.geequery.codegen.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Column;
import javax.persistence.Entity;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="interface")
public class Interface extends DataObject{


	@Id
	@Column(name="id",columnDefinition="char(14)",length=14,nullable=false)
	private String id;

	@Column(name="name",columnDefinition="varchar(50)",length=50)
	private String name;

	@Column(name="description",columnDefinition="varchar(3000)",length=3000)
	private String description;

	@Column(name="folderId",columnDefinition="char(14)",length=14)
	private String folderid;

	@Column(name="url",columnDefinition="varchar(300)",length=300)
	private String url;

	@Column(name="requestMethod",columnDefinition="varchar(50)",length=50)
	private String requestmethod;

	@Column(name="contentType",columnDefinition="varchar(50)",length=50)
	private String contenttype;

	@Lob
	@Column(name="requestHeaders",columnDefinition="clob")
	private String requestheaders;

	@Lob
	@Column(name="requestArgs",columnDefinition="clob")
	private String requestargs;

	@Lob
	@Column(name="responseArgs",columnDefinition="clob")
	private String responseargs;

	@Lob
	@Column(name="example",columnDefinition="clob")
	private String example;

	@Column(name="moduleId",columnDefinition="varchar(50)",length=50)
	private String moduleid;

	@Column(name="projectId",columnDefinition="char(14)",length=14)
	private String projectid;

	@Column(name="lastUpdateTime",columnDefinition="timestamp")
	private Date lastupdatetime;

	@Column(name="createTime",columnDefinition="timestamp")
	private Date createtime;

	@Column(name="dataType",columnDefinition="varchar(30)",length=30)
	private String datatype;

	@Column(name="protocol",columnDefinition="varchar(30)",length=30)
	private String protocol;

	@Column(name="status",columnDefinition="char(10) default 'ENABLE'",length=10)
	private String status;

	public void setId(String obj){
		this.id = obj;
	}

	public String getId(){
		return id;
	}

	public void setName(String obj){
		this.name = obj;
	}

	public String getName(){
		return name;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public void setFolderid(String obj){
		this.folderid = obj;
	}

	public String getFolderid(){
		return folderid;
	}

	public void setUrl(String obj){
		this.url = obj;
	}

	public String getUrl(){
		return url;
	}

	public void setRequestmethod(String obj){
		this.requestmethod = obj;
	}

	public String getRequestmethod(){
		return requestmethod;
	}

	public void setContenttype(String obj){
		this.contenttype = obj;
	}

	public String getContenttype(){
		return contenttype;
	}

	public void setRequestheaders(String obj){
		this.requestheaders = obj;
	}

	public String getRequestheaders(){
		return requestheaders;
	}

	public void setRequestargs(String obj){
		this.requestargs = obj;
	}

	public String getRequestargs(){
		return requestargs;
	}

	public void setResponseargs(String obj){
		this.responseargs = obj;
	}

	public String getResponseargs(){
		return responseargs;
	}

	public void setExample(String obj){
		this.example = obj;
	}

	public String getExample(){
		return example;
	}

	public void setModuleid(String obj){
		this.moduleid = obj;
	}

	public String getModuleid(){
		return moduleid;
	}

	public void setProjectid(String obj){
		this.projectid = obj;
	}

	public String getProjectid(){
		return projectid;
	}

	public void setLastupdatetime(Date obj){
		this.lastupdatetime = obj;
	}

	public Date getLastupdatetime(){
		return lastupdatetime;
	}

	public void setCreatetime(Date obj){
		this.createtime = obj;
	}

	public Date getCreatetime(){
		return createtime;
	}

	public void setDatatype(String obj){
		this.datatype = obj;
	}

	public String getDatatype(){
		return datatype;
	}

	public void setProtocol(String obj){
		this.protocol = obj;
	}

	public String getProtocol(){
		return protocol;
	}

	public void setStatus(String obj){
		this.status = obj;
	}

	public String getStatus(){
		return status;
	}

	public Interface(){
	}

	public Interface(String id){
		this.id = id;
	}


   public enum Field implements jef.database.Field{id,name,description,folderid,url,requestmethod,contenttype,requestheaders,requestargs,responseargs,example,moduleid,projectid,lastupdatetime,createtime,datatype,protocol,status}
}