package com.github.geequery.codegen.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Column;
import javax.persistence.Entity;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="module")
public class Module extends DataObject{


	@Id
	@Column(name="id",columnDefinition="char(14)",length=14,nullable=false)
	private String id;

	@Column(name="name",columnDefinition="varchar(50)",length=50)
	private String name;

	@Column(name="host",columnDefinition="varchar(255)",length=255)
	private String host;

	@Lob
	@Column(name="description",columnDefinition="clob")
	private String description;

	@Column(name="lastUpdateTime",columnDefinition="timestamp")
	private Date lastupdatetime;

	@Column(name="projectId",columnDefinition="char(14)",length=14)
	private String projectid;

	@Column(name="createTime",columnDefinition="timestamp")
	private Date createtime;

	@Lob
	@Column(name="requestHeaders",columnDefinition="clob")
	private String requestheaders;

	@Lob
	@Column(name="requestArgs",columnDefinition="clob")
	private String requestargs;

	public void setId(String obj){
		this.id = obj;
	}

	public String getId(){
		return id;
	}

	public void setName(String obj){
		this.name = obj;
	}

	public String getName(){
		return name;
	}

	public void setHost(String obj){
		this.host = obj;
	}

	public String getHost(){
		return host;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public void setLastupdatetime(Date obj){
		this.lastupdatetime = obj;
	}

	public Date getLastupdatetime(){
		return lastupdatetime;
	}

	public void setProjectid(String obj){
		this.projectid = obj;
	}

	public String getProjectid(){
		return projectid;
	}

	public void setCreatetime(Date obj){
		this.createtime = obj;
	}

	public Date getCreatetime(){
		return createtime;
	}

	public void setRequestheaders(String obj){
		this.requestheaders = obj;
	}

	public String getRequestheaders(){
		return requestheaders;
	}

	public void setRequestargs(String obj){
		this.requestargs = obj;
	}

	public String getRequestargs(){
		return requestargs;
	}

	public Module(){
	}

	public Module(String id){
		this.id = id;
	}


   public enum Field implements jef.database.Field{id,name,host,description,lastupdatetime,projectid,createtime,requestheaders,requestargs}
}