package com.github.geequery.codegen.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.Column;
import javax.persistence.Entity;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="project_log")
public class ProjectLog extends DataObject{


	@Id
	@Column(name="id",columnDefinition="char(14)",length=14,nullable=false)
	private String id;

	@Column(name="userId",columnDefinition="char(14)",length=14)
	private String userid;

	@Column(name="createTime",columnDefinition="timestamp")
	private Date createtime;

	@Lob
	@Column(name="log",columnDefinition="clob")
	private String log;

	@Column(name="projectId",columnDefinition="char(14)",length=14)
	private String projectid;

	@Column(name="action",columnDefinition="varchar(50)",length=50)
	private String action;

	public void setId(String obj){
		this.id = obj;
	}

	public String getId(){
		return id;
	}

	public void setUserid(String obj){
		this.userid = obj;
	}

	public String getUserid(){
		return userid;
	}

	public void setCreatetime(Date obj){
		this.createtime = obj;
	}

	public Date getCreatetime(){
		return createtime;
	}

	public void setLog(String obj){
		this.log = obj;
	}

	public String getLog(){
		return log;
	}

	public void setProjectid(String obj){
		this.projectid = obj;
	}

	public String getProjectid(){
		return projectid;
	}

	public void setAction(String obj){
		this.action = obj;
	}

	public String getAction(){
		return action;
	}

	public ProjectLog(){
	}

	public ProjectLog(String id){
		this.id = id;
	}


   public enum Field implements jef.database.Field{id,userid,createtime,log,projectid,action}
}