package com.github.geequery.codegen.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="share")
public class Share extends DataObject{


	@Id
	@Column(name="id",columnDefinition="char(12)",length=12,nullable=false)
	private String id;

	@Column(name="name",columnDefinition="varchar(50)",length=50)
	private String name;

	@Column(name="createTime",columnDefinition="timestamp")
	private Date createtime;

	@Column(name="userId",columnDefinition="char(12)",length=12)
	private String userid;

	@Column(name="shareAll",columnDefinition="char(3)",length=3)
	private String shareall;

	@Column(name="password",columnDefinition="varchar(20)",length=20)
	private String password;

	@Column(name="moduleIds",columnDefinition="varchar(500)",length=500)
	private String moduleids;

	@Column(name="projectId",columnDefinition="char(12)",length=12)
	private String projectid;

	public void setId(String obj){
		this.id = obj;
	}

	public String getId(){
		return id;
	}

	public void setName(String obj){
		this.name = obj;
	}

	public String getName(){
		return name;
	}

	public void setCreatetime(Date obj){
		this.createtime = obj;
	}

	public Date getCreatetime(){
		return createtime;
	}

	public void setUserid(String obj){
		this.userid = obj;
	}

	public String getUserid(){
		return userid;
	}

	public void setShareall(String obj){
		this.shareall = obj;
	}

	public String getShareall(){
		return shareall;
	}

	public void setPassword(String obj){
		this.password = obj;
	}

	public String getPassword(){
		return password;
	}

	public void setModuleids(String obj){
		this.moduleids = obj;
	}

	public String getModuleids(){
		return moduleids;
	}

	public void setProjectid(String obj){
		this.projectid = obj;
	}

	public String getProjectid(){
		return projectid;
	}

	public Share(){
	}

	public Share(String id){
		this.id = id;
	}


   public enum Field implements jef.database.Field{id,name,createtime,userid,shareall,password,moduleids,projectid}
}