package com.github.geequery.codegen.entity;

import javax.persistence.Table;
import jef.database.DataObject;
import javax.persistence.Id;
import javax.persistence.Column;
import javax.persistence.Entity;
import java.util.Date;
import jef.codegen.support.NotModified;
/**
 * This class was generated by JEF according to the table in database.
 * You need to modify the type of primary key field, to the strategy your own.
 */
@NotModified
@Entity
@Table(name="team")
public class Team extends DataObject{


	@Id
	@Column(name="id",columnDefinition="char(14)",length=14,nullable=false)
	private String id;

	@Column(name="name",columnDefinition="varchar(50)",length=50)
	private String name;

	@Column(name="description",columnDefinition="varchar(300)",length=300)
	private String description;

	@Column(name="userId",columnDefinition="char(14)",length=14)
	private String userid;

	@Column(name="createTime",columnDefinition="timestamp")
	private Date createtime;

	@Column(name="status",columnDefinition="varchar(20) default 'VALID'",length=20)
	private String status;

	public void setId(String obj){
		this.id = obj;
	}

	public String getId(){
		return id;
	}

	public void setName(String obj){
		this.name = obj;
	}

	public String getName(){
		return name;
	}

	public void setDescription(String obj){
		this.description = obj;
	}

	public String getDescription(){
		return description;
	}

	public void setUserid(String obj){
		this.userid = obj;
	}

	public String getUserid(){
		return userid;
	}

	public void setCreatetime(Date obj){
		this.createtime = obj;
	}

	public Date getCreatetime(){
		return createtime;
	}

	public void setStatus(String obj){
		this.status = obj;
	}

	public String getStatus(){
		return status;
	}

	public Team(){
	}

	public Team(String id){
		this.id = id;
	}


   public enum Field implements jef.database.Field{id,name,description,userid,createtime,status}
}