/* Generated By:JavaCC: Do not edit this line. StSqlParserConstants.java */
package jef.database.jsqlparser.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface StSqlParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int K_AS = 5;
  /** RegularExpression Id. */
  int K_BY = 6;
  /** RegularExpression Id. */
  int K_DO = 7;
  /** RegularExpression Id. */
  int K_IS = 8;
  /** RegularExpression Id. */
  int K_IN = 9;
  /** RegularExpression Id. */
  int K_OR = 10;
  /** RegularExpression Id. */
  int K_ON = 11;
  /** RegularExpression Id. */
  int K_ALL = 12;
  /** RegularExpression Id. */
  int K_AND = 13;
  /** RegularExpression Id. */
  int K_ANY = 14;
  /** RegularExpression Id. */
  int K_NOT = 15;
  /** RegularExpression Id. */
  int K_SET = 16;
  /** RegularExpression Id. */
  int K_ASC = 17;
  /** RegularExpression Id. */
  int K_TOP = 18;
  /** RegularExpression Id. */
  int K_END = 19;
  /** RegularExpression Id. */
  int K_DESC = 20;
  /** RegularExpression Id. */
  int K_INTO = 21;
  /** RegularExpression Id. */
  int K_NULL = 22;
  /** RegularExpression Id. */
  int K_LIKE = 23;
  /** RegularExpression Id. */
  int K_ILIKE = 24;
  /** RegularExpression Id. */
  int K_DROP = 25;
  /** RegularExpression Id. */
  int K_JOIN = 26;
  /** RegularExpression Id. */
  int K_LEFT = 27;
  /** RegularExpression Id. */
  int K_FROM = 28;
  /** RegularExpression Id. */
  int K_OPEN = 29;
  /** RegularExpression Id. */
  int K_CASE = 30;
  /** RegularExpression Id. */
  int K_WHEN = 31;
  /** RegularExpression Id. */
  int K_THEN = 32;
  /** RegularExpression Id. */
  int K_ELSE = 33;
  /** RegularExpression Id. */
  int K_SOME = 34;
  /** RegularExpression Id. */
  int K_FULL = 35;
  /** RegularExpression Id. */
  int K_WITH = 36;
  /** RegularExpression Id. */
  int K_RECURSIVE = 37;
  /** RegularExpression Id. */
  int K_TABLE = 38;
  /** RegularExpression Id. */
  int K_WHERE = 39;
  /** RegularExpression Id. */
  int K_USING = 40;
  /** RegularExpression Id. */
  int K_UNION = 41;
  /** RegularExpression Id. */
  int K_GROUP = 42;
  /** RegularExpression Id. */
  int K_BEGIN = 43;
  /** RegularExpression Id. */
  int K_INDEX = 44;
  /** RegularExpression Id. */
  int K_INNER = 45;
  /** RegularExpression Id. */
  int K_LIMIT = 46;
  /** RegularExpression Id. */
  int K_OUTER = 47;
  /** RegularExpression Id. */
  int K_ORDER = 48;
  /** RegularExpression Id. */
  int K_PARTITION = 49;
  /** RegularExpression Id. */
  int K_RIGHT = 50;
  /** RegularExpression Id. */
  int K_DELETE = 51;
  /** RegularExpression Id. */
  int K_CREATE = 52;
  /** RegularExpression Id. */
  int K_SELECT = 53;
  /** RegularExpression Id. */
  int K_OFFSET = 54;
  /** RegularExpression Id. */
  int K_EXISTS = 55;
  /** RegularExpression Id. */
  int K_HAVING = 56;
  /** RegularExpression Id. */
  int K_INSERT = 57;
  /** RegularExpression Id. */
  int K_UPDATE = 58;
  /** RegularExpression Id. */
  int K_VALUES = 59;
  /** RegularExpression Id. */
  int K_ESCAPE = 60;
  /** RegularExpression Id. */
  int K_PRIMARY = 61;
  /** RegularExpression Id. */
  int K_NATURAL = 62;
  /** RegularExpression Id. */
  int K_REPLACE = 63;
  /** RegularExpression Id. */
  int K_BETWEEN = 64;
  /** RegularExpression Id. */
  int K_TRUNCATE = 65;
  /** RegularExpression Id. */
  int K_DISTINCT = 66;
  /** RegularExpression Id. */
  int K_INTERSECT = 67;
  /** RegularExpression Id. */
  int K_CONNECT = 68;
  /** RegularExpression Id. */
  int K_PRIOR = 69;
  /** RegularExpression Id. */
  int K_START = 70;
  /** RegularExpression Id. */
  int K_INTERVAL = 71;
  /** RegularExpression Id. */
  int K_NULLS = 72;
  /** RegularExpression Id. */
  int K_LAST = 73;
  /** RegularExpression Id. */
  int K_OVER = 74;
  /** RegularExpression Id. */
  int S_DOUBLE = 75;
  /** RegularExpression Id. */
  int S_INTEGER = 76;
  /** RegularExpression Id. */
  int DIGIT = 77;
  /** RegularExpression Id. */
  int LINE_COMMENT = 78;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 79;
  /** RegularExpression Id. */
  int S_IDENTIFIER = 80;
  /** RegularExpression Id. */
  int LETTER = 81;
  /** RegularExpression Id. */
  int SPECIAL_CHARS = 82;
  /** RegularExpression Id. */
  int S_CHAR_LITERAL = 83;
  /** RegularExpression Id. */
  int S_QUOTED_IDENTIFIER = 84;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"AS\"",
    "\"BY\"",
    "\"DO\"",
    "\"IS\"",
    "\"IN\"",
    "\"OR\"",
    "\"ON\"",
    "\"ALL\"",
    "\"AND\"",
    "\"ANY\"",
    "\"NOT\"",
    "\"SET\"",
    "\"ASC\"",
    "\"TOP\"",
    "\"END\"",
    "\"DESC\"",
    "\"INTO\"",
    "\"NULL\"",
    "\"LIKE\"",
    "\"ILIKE\"",
    "\"DROP\"",
    "\"JOIN\"",
    "\"LEFT\"",
    "\"FROM\"",
    "\"OPEN\"",
    "\"CASE\"",
    "\"WHEN\"",
    "\"THEN\"",
    "\"ELSE\"",
    "\"SOME\"",
    "\"FULL\"",
    "\"WITH\"",
    "\"RECURSIVE\"",
    "\"TABLE\"",
    "\"WHERE\"",
    "\"USING\"",
    "\"UNION\"",
    "\"GROUP\"",
    "\"BEGIN\"",
    "\"INDEX\"",
    "\"INNER\"",
    "\"LIMIT\"",
    "\"OUTER\"",
    "\"ORDER\"",
    "\"PARTITION\"",
    "\"RIGHT\"",
    "\"DELETE\"",
    "\"CREATE\"",
    "\"SELECT\"",
    "\"OFFSET\"",
    "\"EXISTS\"",
    "\"HAVING\"",
    "\"INSERT\"",
    "\"UPDATE\"",
    "\"VALUES\"",
    "\"ESCAPE\"",
    "<K_PRIMARY>",
    "\"NATURAL\"",
    "\"REPLACE\"",
    "\"BETWEEN\"",
    "\"TRUNCATE\"",
    "\"DISTINCT\"",
    "\"INTERSECT\"",
    "\"CONNECT\"",
    "\"PRIOR\"",
    "\"START\"",
    "\"INTERVAL\"",
    "\"NULLS\"",
    "\"LAST\"",
    "\"OVER\"",
    "<S_DOUBLE>",
    "<S_INTEGER>",
    "<DIGIT>",
    "<LINE_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "<S_IDENTIFIER>",
    "<LETTER>",
    "<SPECIAL_CHARS>",
    "<S_CHAR_LITERAL>",
    "<S_QUOTED_IDENTIFIER>",
    "\";\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\"@\"",
    "\"*\"",
    "\"?\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"<>\"",
    "\"!=\"",
    "\"||\"",
    "\"|\"",
    "\"&\"",
    "\"+\"",
    "\"-\"",
    "\"/\"",
    "\"%\"",
    "\"^\"",
    "\"{d\"",
    "\"}\"",
    "\"{t\"",
    "\"{ts\"",
    "\"{fn\"",
    "\"@@\"",
  };

}
